--------------------------------------------------------------
-- correlation
--------------------------------------------------------------

CREATE TABLE WMPRTXREF (
	EXTERNALID	VARCHAR2(300) NOT NULL,
	XREFGROUP	SMALLINT NOT NULL,
	INSTANCEID	CHAR(38) NOT NULL,
	UPDATEID	CHAR(255),
	primary key (EXTERNALID, XREFGROUP)
	);



--------------------------------------------------------------
-- queue
--------------------------------------------------------------

CREATE TABLE PRTQUEUECONTENT (
	INSTANCEID	CHAR(38) NOT NULL,
	EVENTID		CHAR(32) NOT NULL,
	EVENT		BLOB,
	primary key (EVENTID)
	);

CREATE TABLE PRTQUEUE (
	INSTANCEID	CHAR(38) NOT NULL,
	STEPID		VARCHAR2(255) NOT NULL,
	QUEUE		BLOB,
	SERVERID	VARCHAR2(255)
	);

CREATE UNIQUE INDEX PRTQUEUE_IDX on PRTQUEUE (INSTANCEID, STEPID, SERVERID);

CREATE TABLE PRTQUEUELOCK (
	LOCKID		VARCHAR2(100) NOT NULL,
	HOLDER		CHAR(32) NOT NULL,
	LOCKSTART	DATE,
	primary key (LOCKID)
	);



--------------------------------------------------------------
-- process
--------------------------------------------------------------

CREATE TABLE PRTPROCESS (
	INSTANCEID	CHAR(38) NOT NULL,
	STATUS		INTEGER NOT NULL,
	MODELID		VARCHAR2(255) NOT NULL,
	STACK		BLOB,
	OLDSTACK	VARCHAR2(255),
	SERVERID	VARCHAR2(255),
	CURRENTTIME	DATE
	);

CREATE UNIQUE INDEX PRTPROCESS_IDX on PRTPROCESS (INSTANCEID, SERVERID);

CREATE TABLE PRTPROCLOCK (
	LOCKID		VARCHAR2(100) NOT NULL,
	HOLDER		CHAR(32),
	LOCKSTART	DATE,
	primary key(LOCKID)
	);

CREATE TABLE WMPRTSTORE (
	INSTANCEID	CHAR(38) NOT NULL,
	PROCESSKEY	VARCHAR2(64),
	TRACKCOUNT	SMALLINT NOT NULL,
	NSUBRUNNING	SMALLINT,
	primary key (INSTANCEID)
	);



--------------------------------------------------------------
-- step state
--------------------------------------------------------------

CREATE TABLE PRTSTEPSTATE (
	INSTANCEID			CHAR(38),
	STEPID				VARCHAR2(255),
	NEXTSTEPITERATION	SMALLINT,
	TIMEOUTID			CHAR(32),
	JOINSTATE			BLOB,
	SERVERID			VARCHAR2(255)
	);

CREATE UNIQUE INDEX PRTSTEPSTATE_IDX on PRTSTEPSTATE (INSTANCEID, STEPID, SERVERID);

CREATE TABLE PRTSTEPLOCK (
	LOCKID		VARCHAR2(100) NOT NULL,
	HOLDER		CHAR(32),
	LOCKSTART	DATE,
	primary key (LOCKID)
	);

CREATE TABLE PRTMODELINFO(
	PROCESSKEY		VARCHAR2(64) NOT NULL,
	ENABLED			SMALLINT DEFAULT 0
	);



--------------------------------------------------------------
-- timeouts, instance iterations, step suspension
--------------------------------------------------------------

CREATE TABLE PRTTIMERENTRY (
	PROCESSID		CHAR(38),
	STEPID			VARCHAR2(255),
	STEPITERATION	SMALLINT,
	EXPIRES			DATE,
	TIMERDELAY		LONG,
	TIMERTYPE		SMALLINT,
	CLASSIFICATION	CHAR(32),
	THREADID		VARCHAR2(255)
	);

CREATE TABLE PRTTIMEOUT (
	TIMEOUTID		CHAR(32),
	INSTANCEID		CHAR(38),
	STEPID			VARCHAR2(255),
	STEPITERATION	SMALLINT,
	EXPIRES			DATE,
	SERVERID		VARCHAR2(255)
	);

CREATE TABLE PRTINSTANCEITER (
	INSTANCEID		CHAR(32),
	LASTITERATION	SMALLINT,
	SERVERID		VARCHAR2(255)
	);

CREATE TABLE PRTSTEPSUSPENSION (
	INSTANCEID	CHAR(38),
	STEPID		VARCHAR2(255),
	SERVERID	VARCHAR2(255)
	);



--------------------------------------------------------------
-- global data
--------------------------------------------------------------

CREATE TABLE PRTGLOBALDATA  (
	INSTANCEID CHAR(38),
	VARNAME    VARCHAR2(255),
	IDATA      BLOB
	);

CREATE UNIQUE INDEX PRTGLOBALDATA_IDX on PRTGLOBALDATA (INSTANCEID, VARNAME);

CREATE TABLE PRTADDRESS  (
	INSTANCEID	CHAR(38),
	LINKNAME    VARCHAR2(255),
	ADDRESS     BLOB
	);

CREATE UNIQUE INDEX PRTADDRESS_IDX on PRTADDRESS(INSTANCEID, LINKNAME);

CREATE TABLE PRTWSREQUESTS(
	INSTANCEID	CHAR(38),
	SOURCEDOC   VARCHAR2(255)
	);

CREATE UNIQUE INDEX PRTWSREQUESTS_IDX on PRTWSREQUESTS(INSTANCEID, SOURCEDOC);



COMMIT;
