CREATE TABLE BOOK_ORDER (
   COURSE_TITLE VARCHAR2 (80) NOT NULL ,
   COURSE_ID VARCHAR2 (20) NOT NULL ,
   ORDER_DATE VARCHAR2 (40) NOT NULL ,
   BOOK_TITLE VARCHAR2 (120) NOT NULL ,
   BOOK_AUTHOR VARCHAR2 (80) NOT NULL ,
   ISBN_NO VARCHAR2 (20) NOT NULL
)
;

