CREATE SEQUENCE OrderID_SEQ INCREMENT BY 1 MINVALUE 1
/
CREATE TABLE Orders (
 OrderID INT NOT NULL,
 Title VARCHAR (5),
 FirstName VARCHAR (50),
 Surname VARCHAR (50),
 Field1 VARCHAR (100),
 Field2 VARCHAR (50),
 Field3 VARCHAR (10),
 Field4 VARCHAR (50),
 PONO VARCHAR (50),
 CustID VARCHAR (50),
 PRIMARY KEY (OrderID) 
)
/
CREATE OR REPLACE TRIGGER NEXT_OrderID
BEFORE INSERT OR UPDATE OF OrderID ON Orders
FOR EACH ROW
BEGIN
  SELECT OrderID_SEQ.NEXTVAL
    INTO :new.OrderID
    FROM dual ;
End ;
/
;