CREATE TABLE CUSTOMER_INFO (
   COMPANYNAME VARCHAR2 (40) NOT NULL ,
   STREETNAME VARCHAR2 (40) NOT NULL ,
   CITYNAME VARCHAR2 (40) NOT NULL ,
   STATENAME VARCHAR2 (20) NOT NULL ,
   ZIPCODE VARCHAR2 (5) NOT NULL 
)
;

