
CREATE TABLE SRC_ORDERS (
	ORDER_NO VARCHAR2 (20) NOT NULL ,
	CUSTOMER_NO VARCHAR2 (20) NULL ,
	ORDER_DATE DATE NULL ,
	ORDER_CURRENCY VARCHAR2 (10) NULL ,
	SHIPPING_METHOD VARCHAR2 (20) NULL ,
	PRIMARY KEY (ORDER_NO)
)
/

CREATE SEQUENCE ORDER_DET_NO_SEQ INCREMENT BY 1 MINVALUE 1
/

CREATE TABLE SRC_ORDER_DETAILS (
	ORDER_DET_NO VARCHAR2 (20) UNIQUE ,
	ORDER_NO VARCHAR2 (20) NOT NULL ,
	LINE_NO int NOT NULL ,
	PRODUCT_NO VARCHAR2 (20) NULL ,
	QUANTITY int NULL ,
	UNIT_MEASURE VARCHAR2 (5) NULL ,
	UNIT_PRICE NUMBER (9) NULL ,
	DISCOUNT NUMBER (9) NULL ,
	PRIMARY KEY (ORDER_DET_NO)
)
/

CREATE TABLE SRC_ORDER_PRODUCTS (
	PRODUCT_NO VARCHAR2 (20) NOT NULL ,
	PRODUCT_NAME VARCHAR2 (50) NULL ,
	PRODUCT_DESCRIPTION VARCHAR2 (255) ,
	UNIT_PRICE NUMBER (9) NULL ,
	PRIMARY KEY (PRODUCT_NO)
) 
/

CREATE TABLE SRC_CUSTOMERS (
	CUSTOMER_NO VARCHAR2 (20) NULL ,
	CUSTOMER_NAME VARCHAR2 (40) NULL 
)
/

CREATE TABLE TGT_WAREHOUSE_PRODUCTS (
	PRODUCT_NO VARCHAR2 (20) NOT NULL ,
	PRODUCT_NAME VARCHAR2 (50) NULL ,
	PRODUCT_DESCRIPTION VARCHAR2 (255) ,
	UNIT_PRICE NUMBER (9) NULL ,
	WAREHOUSE_NO VARCHAR2 (20) NULL ,
	BIN_NO VARCHAR2 (20) NULL ,
	REORDER_LEVEL int NULL ,
	LEAD_TIME int NULL ,
	PRIMARY KEY (PRODUCT_NO)
) 
/

CREATE SEQUENCE PICK_LIST_NO_SEQ INCREMENT BY 1 MINVALUE 1
/

CREATE TABLE TGT_PICK_LIST (
	PICK_LIST_NO VARCHAR2 (20) UNIQUE ,
	PRODUCT_NO VARCHAR2 (20) NOT NULL ,
	PO_NUMBER VARCHAR2 (20) NULL ,
	UNITS_ORDERED int NULL ,
	UNIT_MEASURE VARCHAR2 (5) NULL ,
	PRIMARY KEY (PICK_LIST_NO, PRODUCT_NO)
)
/

CREATE OR REPLACE TRIGGER NEXT_TGT_PICK_LIST
BEFORE INSERT OR UPDATE OF PICK_LIST_NO ON TGT_PICK_LIST
FOR EACH ROW
BEGIN
  SELECT PICK_LIST_NO_SEQ.NEXTVAL
    INTO :new.PICK_LIST_NO
    FROM dual ;
End ;
/

CREATE OR REPLACE TRIGGER NEXT_ORDER_DET_NO
BEFORE INSERT OR UPDATE OF ORDER_DET_NO ON SRC_ORDER_DETAILS
FOR EACH ROW
BEGIN
  SELECT ORDER_DET_NO_SEQ.NEXTVAL
    INTO :new.ORDER_DET_NO
    FROM dual ;
End ;
/

CREATE TABLE TGT_CUSTOMERS (
	CUSTOMER_NO VARCHAR2 (20) NULL ,
	CUSTOMER_NAME VARCHAR2 (40) NULL 
)
/
INSERT INTO SRC_CUSTOMERS VALUES ('1', 'Montana-Jerky');
INSERT INTO SRC_CUSTOMERS VALUES ('100', 'Maine Lobster Co');

COMMIT;