CREATE TABLE ORDER_HEADER (
   ORDER_ID VARCHAR2 (20) NOT NULL ,
   TRANSACTION_ID VARCHAR2 (30) NOT NULL ,
   ORDER_DATE VARCHAR2 (40) NOT NULL ,
   TOTAL_COST VARCHAR2 (20) NOT NULL ,
   IS_VALID VARCHAR2 (10) NOT NULL ,
   SENDER_ID VARCHAR2 (20) NOT NULL ,
   RECEIVER_ID VARCHAR2 (20) NOT NULL
)
/
CREATE TABLE ORDER_DETAILS (
   ORDER_ID VARCHAR2 (20) NOT NULL ,
   TRANSACTION_ID VARCHAR2 (30) NOT NULL ,
   SKU VARCHAR2 (40) NOT NULL ,
   QUANTITY VARCHAR2 (20) NOT NULL
)
;

