<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFIYXNoQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0SGFzaEN1cnNvcigpOwoK
U3RyaW5nIGZpbGVOYW1lID0gIiI7ClN0cmluZyBpblN0ciA9ICIiOwpieXRlW10gYnl0ZXMgPSBu
dWxsOyAKCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZU5hbWUiKSkgCnsKCWZpbGVOYW1lID0g
KFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CmlmIChpZGNQaXBlbGluZS5maXJzdCgi
dXNlckRhdGEiKSkKewoJaW5TdHIgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0g
CmlmIChpZGNQaXBlbGluZS5maXJzdCgiYnl0ZXMiKSkKewoJYnl0ZXMgPSAoYnl0ZVtdKWlkY1Bp
cGVsaW5lLmdldFZhbHVlKCk7Cn0KCnRyeSB7CglGaWxlT3V0cHV0U3RyZWFtIGZvcyA9IG5ldyBG
aWxlT3V0cHV0U3RyZWFtKCBuZXcgRmlsZShmaWxlTmFtZSkpOwoJaWYgKGluU3RyICE9IG51bGwg
JiYgIWluU3RyLmVxdWFscygiIikpCgl7CgkJZm9zLndyaXRlKGluU3RyLmdldEJ5dGVzKCksIDAs
IGluU3RyLmxlbmd0aCgpKTsKCQlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigicmV0dXJuQ29kZSIs
IEludGVnZXIudG9TdHJpbmcoMCkpOwoJCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJyZXR1cm5N
c2ciLCAiU3VjY2Vzc2Z1bGx5IHdyaXRlIGZpbGUgIitmaWxlTmFtZSk7Cgl9CglpZiAoYnl0ZXMg
IT0gbnVsbCApCgl7CgkJZm9zLndyaXRlKGJ5dGVzLCAwLCBieXRlcy5sZW5ndGgpOwoJCWlkY1Bp
cGVsaW5lLmluc2VydEFmdGVyKCJyZXR1cm5Db2RlIiwgSW50ZWdlci50b1N0cmluZygwKSk7CgkJ
aWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInJldHVybk1zZyIsICJTdWNjZXNzZnVsbHkgd3JpdGUg
ZmlsZSAiK2ZpbGVOYW1lKTsKCX0KCQoJZm9zLmNsb3NlKCk7Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBl
KQp7CgkvL3Rocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwoJaWRjUGlwZWxpbmUuaW5zZXJ0
QWZ0ZXIoInJldHVybkNvZGUiLCBJbnRlZ2VyLnRvU3RyaW5nKC0xKSk7CglpZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigicmV0dXJuTXNnIiwgIkZhaWxlZCB0byB3cml0ZSBmaWxlICIrZmlsZU5hbWUg
KyIgLSAiK2UudG9TdHJpbmcoKSk7Cn0K</value>
</Values>
